name: 'Hello World Back4App'
description: 'Runs the Back4App CLI'
inputs:
  appname:
    description: 'The App Name'
    required: true
  appid:
    description: 'The App ID on Back4App'
    required: true
  accountkey:
    description: 'Account key for admin authentication'
    required: true
  email:
    description: 'The email of the admin'
    required: true
runs:
  using: 'docker'
  image: './Dockerfile'
  args:
    - ${{ inputs.appid }}
    - ${{ inputs.accountkey }}
    - ${{ inputs.email }}
    - ${{ inputs.appname }}
