enum QueryCacheGroups {
  GET_ALBUM = "GET_ALBUM",
  GET_IMAGES_BY_ID = "GET_IMAGES_BY_ID",
  GET_IMAGE_BY_ID = "GET_IMAGE_BY_ID",
  GET_USER_BY_ID = "GET_USER_BY_ID",
  GET_USERS_BY_EMAIL = "GET_USERS_BY_EMAIL",
  GET_USER_BY_EMAIL = "GET_USER_BY_EMAIL",
  GET_RELATED_USER_EMAILS = "GET_RELATED_USER_EMAILS",
  GET_DUPLICATES = "GET_DUPLICATES",
  GET_ALL_ALBUMS_INFINITE = "GET_ALL_ALBUMS_INFINITE",
  GET_ALL_IMAGES_INFINITE = "GET_ALL_IMAGES_INFINITE",
  GET_IMAGES_BY_ID_INFINITE = "GET_IMAGES_BY_ID_INFINITE",
  GET_IMAGES_BY_OWNER_INFINITE = "GET_IMAGES_BY_OWNER_INFINITE",
  GET_ALBUM_CHANGE_NOTIFICATIONS = "GET_ALBUM_CHANGE_NOTIFICATIONS",
}

export default QueryCacheGroups;
