name: Deploy Dev/Test

on:
  workflow_run:
    workflows: ["CodeQL"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build and deploy the project on dev/test environment
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        # Checks-out under $GITHUB_WORKSPACE
      - name: Check out
        id: checkout
        uses: actions/checkout@v3

      # Runs the docker container with the right params
      - name: Run Docker Script
        id: docker
        uses: ./.github/actions/deploy
        with:
          appid: 'GkKaaxNRxTc1XONlpCizJtzVIzkWYI6ZLxrLylT4'
          appname: 'Shadowboxx Dev/Test'
          accountkey: ${{ secrets.B4A_ACCOUNT_KEY }}
          email: 'b4a@nicholasjestrada.aleeas.com'
